# Generated by Django 5.0 on 2023-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='Дата и время создания')),
                ('datetime_deadline', models.DateTimeField(verbose_name='Дата и время к которому должна быть выполнена')),
                ('priority', models.CharField(choices=[('red', 'Высокий'), ('yellow', 'Средний'), ('green', 'Низкий')], default='Низкий', max_length=7, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('wait', 'Ожидает выполнения'), ('done', 'Выполнена'), ('doing', 'В процессе выполнения')], default='Ожидает выполнения', max_length=21, verbose_name='Статус')),
                ('task_name', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
